In [1]:
import nltk 
from nltk import pos_tag
nltk.download('punkt')
from nltk.tokenize import sent_tokenize, word_tokenize
nltk.download("stopwords")
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer
nltk.download('wordnet')
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')
nltk.download('omw-1.4')
from nltk.stem import WordNetLemmatizer
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder
from nltk import ngrams
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from nltk.tokenize import word_tokenize
from nltk.collocations import *
from nltk.collocations import BigramCollocationFinder,TrigramCollocationFinder,QuadgramCollocationFinder


[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\mahnaz\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\mahnaz\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\mahnaz\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\mahnaz\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\mahnaz\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


In [2]:
def preprocess(matn_vorodi):
    
    global stemmer_words
    global filtered_list
    global fixd_stemmer_words
    global text
    global token
    
    text = open(matn_vorodi, "r")
    
    text=text.read()
    token=word_tokenize(text)
    
    stop_words = set(stopwords.words("english"))
    
    filtered_list = []
    for word in token:
        if word.casefold() not in stop_words:
             filtered_list.append(word)
                
    stemmer = PorterStemmer()
    stemmer_words = [stemmer.stem(word) for word in filtered_list]
    
    cc=stemmer_words.count('.')
    for i in range(cc):
        stemmer_words.remove('.')
        
    cx=stemmer_words.count(',')
    for i in range(cx):
        stemmer_words.remove(',')
    
    fixd_stemmer_words=' '.join(stemmer_words)
    
    print(fixd_stemmer_words)
    
    
def bag_of_words():
    
    global unic_text
    global bag_of_text
    
    unic_text=[]
    for i in stemmer_words:
        if i not in unic_text:
            unic_text.append(i)
    print('unic_text : ', unic_text)
    print("\n")
    bag_of_text = {}
    for i in stemmer_words:
        word = i.lower()
        if word in bag_of_text:
            bag_of_text[word] += 1
        else:
            bag_of_text[word] = 1

    print ('bag_of_text : ',bag_of_text)
    
    n_words_set=len(bag_of_text.keys())
    b=list(bag_of_text.values())
    df_tf=pd.DataFrame(np.zeros((1, n_words_set)),columns=bag_of_text.keys())
    i=0
    for w in bag_of_text.keys():
        df_tf[w] = b[i]
        i+=1
    return df_tf
    
    
def N_gram(n):
    
    
    CountVec = CountVectorizer(ngram_range=(n,n))

    Count_data = CountVec.fit_transform([fixd_stemmer_words])
    
    cv_dataframe=pd.DataFrame(Count_data.toarray(),columns=CountVec.get_feature_names())
    print (cv_dataframe)
    
    print( )

    print("tf_idf Without Smoothing:")
    print("\n")
    
    tf_idf_vec = TfidfVectorizer(use_idf=True, 
                            smooth_idf=False,  
                            ngram_range=(n,n),stop_words='english')

    tf_idf_data = tf_idf_vec.fit_transform([fixd_stemmer_words])


    tf_idf_dataframe=pd.DataFrame(tf_idf_data.toarray(),columns=tf_idf_vec.get_feature_names())
    print(tf_idf_dataframe)
    print("\n")

    tf_idf_vec_smooth = TfidfVectorizer(use_idf=True,  
                            smooth_idf=True,  
                            ngram_range=(n,n),stop_words='english')


    tf_idf_data_smooth = tf_idf_vec_smooth.fit_transform([fixd_stemmer_words])

    print("tf_idf With Smoothing:")
    print("\n")
    tf_idf_dataframe_smooth=pd.DataFrame(tf_idf_data_smooth.toarray(),columns=tf_idf_vec_smooth.get_feature_names())
    print (tf_idf_dataframe_smooth)
    
    
def tf_idf():
    
    n_docs = 1    
    n_words_set = len(unic_text)

    df_tf = pd.DataFrame(np.zeros((n_docs, n_words_set)), columns=unic_text)

    for w in stemmer_words:
        df_tf[w] = df_tf[w] + (1 / len(token))
        
    dictt={}
    column=df_tf.columns
    for i in column:
        dictt[i]=df_tf[i][0]

    print(dictt)
    
    return df_tf
    
    
def part_of_speech():
    
    text_tag=pos_tag(unic_text)
    print(text_tag)

    
    encoder = OneHotEncoder(sparse=False)
    onehot = encoder.fit_transform(text_tag)
    print('\n')
    print('onehot encoder: ')
    print('\n')
    print(onehot)


In [3]:
preprocess('D://textt.txt')

muad'dib learn rapidli first train learn first lesson basic trust could learn 's shock find mani peopl believ learn mani believ learn difficult


In [4]:
bag_of_words()

unic_text :  ["muad'dib", 'learn', 'rapidli', 'first', 'train', 'lesson', 'basic', 'trust', 'could', "'s", 'shock', 'find', 'mani', 'peopl', 'believ', 'difficult']


bag_of_text :  {"muad'dib": 1, 'learn': 5, 'rapidli': 1, 'first': 2, 'train': 1, 'lesson': 1, 'basic': 1, 'trust': 1, 'could': 1, "'s": 1, 'shock': 1, 'find': 1, 'mani': 2, 'peopl': 1, 'believ': 2, 'difficult': 1}


muad'dib  learn  rapidli  first  train  lesson  basic  trust  could  's  \
0         1      5        1      2      1       1      1      1      1   1   

   shock  find  mani  peopl  believ  difficult  
0      1     1     2      1       2          1

In [5]:
N_gram(1)

   basic  believ  could  dib  difficult  find  first  learn  lesson  mani  \
0      1       2      1    1          1     1      2      5       1     2   

   muad  peopl  rapidli  shock  train  trust  
0     1      1        1      1      1      1  

tf_idf Without Smoothing:


      basic    believ       dib  difficult     learn    lesson      mani  \
0  0.152499  0.304997  0.152499   0.152499  0.762493  0.152499  0.304997   

       muad     peopl   rapidli     shock     train     trust  
0  0.152499  0.152499  0.152499  0.152499  0.152499  0.152499  


tf_idf With Smoothing:


      basic    believ       dib  difficult     learn    lesson      mani  \
0  0.152499  0.304997  0.152499   0.152499  0.762493  0.152499  0.304997   

       muad     peopl   rapidli     shock     train     trust  
0  0.152499  0.152499  0.152499  0.152499  0.152499  0.152499  


C:\Users\mahnaz\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)
C:\Users\mahnaz\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)
C:\Users\mahnaz\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [6]:
tf_idf()

{"muad'dib": 0.018867924528301886, 'learn': 0.09433962264150943, 'rapidli': 0.018867924528301886, 'first': 0.03773584905660377, 'train': 0.018867924528301886, 'lesson': 0.018867924528301886, 'basic': 0.018867924528301886, 'trust': 0.018867924528301886, 'could': 0.018867924528301886, "'s": 0.018867924528301886, 'shock': 0.018867924528301886, 'find': 0.018867924528301886, 'mani': 0.03773584905660377, 'peopl': 0.018867924528301886, 'believ': 0.03773584905660377, 'difficult': 0.018867924528301886}


muad'dib    learn   rapidli     first     train    lesson     basic  \
0  0.018868  0.09434  0.018868  0.037736  0.018868  0.018868  0.018868   

      trust     could        's     shock      find      mani     peopl  \
0  0.018868  0.018868  0.018868  0.018868  0.018868  0.037736  0.018868   

     believ  difficult  
0  0.037736   0.018868

In [7]:
part_of_speech()

[("muad'dib", 'NN'), ('learn', 'NN'), ('rapidli', 'NN'), ('first', 'RB'), ('train', 'VB'), ('lesson', 'NN'), ('basic', 'JJ'), ('trust', 'NN'), ('could', 'MD'), ("'s", 'POS'), ('shock', 'NN'), ('find', 'VBP'), ('mani', 'JJ'), ('peopl', 'NN'), ('believ', 'NN'), ('difficult', 'JJ')]


onehot encoder: 


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 